### ISSUE TITLE
need help to make 480p cheat for GT4

### ISSUE THREAD

**Issue by kanexu1985** [CookiePLMonster/Console-Cheat-Codes#15]
Hi CookiePLMonster,

I'm playing a Chinese version of GT4(serial: SCAJ-30007, CRC: 7ABDBB5E) on PCSX2, the available cheat code of starting game from 480p from the internet is not working on my version.
I don't want to be a person to just ask for an existing patch, and I tried to make if from my own.
I've downloaded Cheat Engine and try to scan the value while I swithing the display option from Normal to 480p, but I just cannnot lock any address.

I see you've publiched the 480p cheat for various GT4 versions, how did you do that, could you please share some experience?

Thanks!

**Comment by CookiePLMonster** [comment]
Hey,

With Gran Turismo 4 it's a little more complicated than the usual, because the game executable is encrypted. You'll most likely need to grab both the Chinese version and one of the versions supported by the cheat, and peek into the save state memory dump via a disassembler to find the code I patched - then look for the exact same code in the memory dump of the Chinese version.

**Comment by kanexu1985** [comment]
thanks for the reply. It's more complicated then I thought. I'll have it a try, not sure if I can do it, but anyway thank you for sharing the experience!

**Comment by CookiePLMonster** [comment]
Yeah it's tricky, since the variable that controls the 480p toggle is in dynamic memory - so you could find the flag via Cheat Engine, but then on the next boot it's likely to be located elsewhere. Therefore, the only reliable approach is to patch the code setting its default.

I'll close it now as resolved, but feel free to reopen if you think it's beneficial.
